name: main
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  PYTHON_VERSION: "3.10"
  
jobs:
  docs-pipeline:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Prepare dependencies
        run: make deps

      - name: Deploy to gh-pages branch
        run: mkdocs gh-deploy --force
